import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="siteHeader">
          <div className="container">
            <a href="/" className="brand">
              <div className="logo" aria-hidden></div>
              <span className="siteTitle">Cool Cars</span>
            </a>
          </div>
        </header>

        {children}

        <footer className="siteFooter">
          <div className="container">© {new Date().getFullYear()} Cool Cars</div>
        </footer>
      </body>
    </html>
  );
}
